import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer } from 'recharts';
import type { RecipeIdea } from './App'; 

const COLORS = ['#10b981', '#3b82f6', '#f59e0b', '#ef4444'];

const RecipeModal = ({ recipe, onClose }: { recipe: RecipeIdea; onClose: () => void }) => {
  const servings = recipe.servings || 1;
  const co2PerServing = recipe.estimated_co2 / servings;
  
  const co2SplitPerServing = (recipe.co2_split || []).map(item => ({
    name: item.name,
    value: item.value / servings
  }));

  const weightLabel = recipe.servingWeight ? ` (${recipe.servingWeight})` : '';

  // Determine which ingredient list to use
  const hasSpoonacularIngredients = recipe.extendedIngredients && recipe.extendedIngredients.length > 0;
  const displayIngredients = hasSpoonacularIngredients 
    ? recipe.extendedIngredients 
    : recipe.inferred_ingredients;

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/40 backdrop-blur-sm" onClick={onClose}>
      <div 
        className="bg-[#8B9D44] border-4 border-[#6B7D34] rounded-2xl shadow-2xl max-w-5xl w-full p-1 animate-in zoom-in-95" 
        onClick={e => e.stopPropagation()}
      >
        <div className="bg-white p-6 md:p-10 flex flex-col md:row relative max-h-[90vh] overflow-y-auto rounded-2xl text-offblack">
          <button onClick={onClose} className="absolute top-2 right-4 text-3xl font-serif text-gray-400 hover:text-black">×</button>

          <div className="flex flex-col md:flex-row">
            <div className="md:w-3/5 pr-0 md:pr-8 border-b md:border-b-0 md:border-r border-gray-200">
              <h2 className="text-4xl font-barnaby underline decoration-2 uppercase tracking-wide mb-6 text-offblack">{recipe.title}</h2>
              
              <div className="flex gap-4 mb-8 text-xs font-bold text-gray-500 uppercase">
                <span>Prep: {recipe.prep_time}m</span>
                <span>Cook: {recipe.cook_time}m</span>
                <span className="text-green-600">CO2 / serving{weightLabel}: {co2PerServing.toFixed(2)}kg</span>
              </div>

              <div className="mb-8">
                <h3 className="text-xl font-bold mb-4 flex justify-between items-center text-offblack">
                  Ingredients
                  {recipe.calories && (
                    <span className="text-sm font-normal text-gray-400 italic">
                      ~{Math.round(recipe.calories)} kcal / serving{weightLabel}
                    </span>
                  )}
                </h3>

                {/* FALLBACK LOGIC */}
                {!hasSpoonacularIngredients && (
                  <div className="bg-orange-50 border-l-4 border-orange-400 p-3 mb-4 rounded-r-lg text-xs text-orange-800">
                    <p className="font-bold">Ingredients are unavailable on Spoonacular.</p>
                    <p>Showing an <strong>educated guess</strong> generated by ASI:One AI.</p>
                  </div>
                )}

                <ul className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-2 mb-6">
                  {displayIngredients?.map((ing, i) => (
                    <li key={i} className="text-sm text-gray-600 capitalize border-b border-gray-50 pb-1">
                      <span className="font-bold text-olive">{ing.amount} {ing.unit}</span> {ing.name}
                    </li>
                  ))}
                </ul>
              </div>
              
              <h3 className="text-xl font-bold mb-4 text-offblack">Preparation:</h3>
              <div className="space-y-4">
                {recipe.instructions.map((step, i) => (
                  <div key={i} className="flex gap-3 text-gray-700 text-sm leading-relaxed">
                    <span className="font-bold text-[#8B9D44]">{i + 1}.</span>
                    <p>{step}</p>
                  </div>
                ))}
              </div>
            </div>

            <div className="md:w-2/5 pl-0 md:pl-8 pt-8 md:pt-0 flex flex-col items-center">
              <div className="w-full mb-8">
                <h4 className="text-xl font-sans text-offblack border-b border-gray-100 pb-2 mb-4">Macros / serving{weightLabel}</h4>
                <div className="grid grid-cols-3 gap-2">
                  {recipe.macros?.map((m, i) => (
                    <div key={i} className="text-center bg-gray-50 p-2 rounded-lg border border-gray-100">
                      <p className="text-[12px] text-offblack uppercase tracking-tighter">{m.name}</p>
                      <p className="font-bold text-lg text-offblack">{Math.round(m.value)}g</p>
                    </div>
                  ))}
                </div>
              </div>

              <div className="bg-[#8B9D44] p-3 rounded-sm w-full mb-6 shadow-inner">
                <div className="h-48 w-full bg-white/20 rounded">
                  <ResponsiveContainer width="100%" height="100%">
                    <PieChart>
                      <Pie data={co2SplitPerServing} dataKey="value" nameKey="name" cx="50%" cy="50%" outerRadius={85}>
                        {co2SplitPerServing.map((_, i) => <Cell key={i} fill={COLORS[i % COLORS.length]} />)}
                      </Pie>
                      <Tooltip />
                    </PieChart>
                  </ResponsiveContainer>
                </div>
              </div>

              <div className="w-full mb-8">
                <h4 className="text-2xl font-sans text-offblack border-b border-gray-100 pb-2 mb-3">Impact / serving{weightLabel}</h4>
                {co2SplitPerServing.map((item, i) => (
                  <div key={i} className="flex justify-between text-md font-sans text-gray-500 mb-1">
                    <span>{item.name}</span>
                    <span className="font-bold">{item.value.toFixed(2)}kg</span>
                  </div>
                ))}
              </div>

              <div className="border-4 border-[#8B9D44] p-1 shadow-lg w-full">
                <img src={recipe.image_url} className="w-full h-44 object-cover" alt={recipe.title} />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default RecipeModal;